module.exports = [
  {
    id: "knee-premium",
    name: "Premium Knee Implant",
    manufacturer: "Smith & Nephew",
    origin: "Imported",
    tier: "Premium",
    description: "High-quality imported knee implant with advanced materials and superior longevity",
    price: 150000,
    warranty: 15,
    longevity: 20,
    materials: ["Oxidized Zirconium", "Highly Cross-linked Polyethylene"],
    compatibleSurgeries: ["knee-replacement-total", "knee-replacement-partial"],
    features: ["Wear-resistant surface", "Reduced friction", "Minimizes metal ion release", "Excellent range of motion"]
  },
  {
    id: "knee-standard",
    name: "Standard Knee Implant",
    manufacturer: "Meril Life",
    origin: "Indian",
    tier: "Standard",
    description: "Reliable Indian-made knee implant with good durability and performance",
    price: 80000,
    warranty: 10,
    longevity: 15,
    materials: ["Cobalt-Chromium Alloy", "Polyethylene"],
    compatibleSurgeries: ["knee-replacement-total", "knee-replacement-partial", "knee-revision"],
    features: ["Good wear resistance", "Stable fixation", "Cost-effective", "Proven track record"]
  },
  {
    id: "knee-economy",
    name: "Economy Knee Implant",
    manufacturer: "Sushrut Surgicals",
    origin: "Indian",
    tier: "Economy",
    description: "Cost-effective knee implant with acceptable performance for budget-conscious patients",
    price: 50000,
    warranty: 5,
    longevity: 10,
    materials: ["Stainless Steel", "Polyethylene"],
    compatibleSurgeries: ["knee-replacement-total"],
    features: ["Budget-friendly", "Suitable for less active patients", "Made in India"]
  },
  {
    id: "hip-premium",
    name: "Premium Hip Implant",
    manufacturer: "DePuy Synthes",
    origin: "Imported",
    tier: "Premium",
    description: "High-quality imported hip implant with ceramic bearing surfaces for maximum longevity",
    price: 180000,
    warranty: 15,
    longevity: 25,
    materials: ["Titanium Alloy", "Ceramic-on-Ceramic Bearing"],
    compatibleSurgeries: ["hip-replacement-total", "hip-resurfacing"],
    features: ["Minimal wear", "Reduced risk of osteolysis", "Excellent biocompatibility", "Ideal for younger, active patients"]
  },
  {
    id: "hip-standard",
    name: "Standard Hip Implant",
    manufacturer: "Inor Medical",
    origin: "Indian",
    tier: "Standard",
    description: "Reliable Indian-made hip implant with metal-on-polyethylene bearing surfaces",
    price: 90000,
    warranty: 10,
    longevity: 15,
    materials: ["Titanium Alloy", "Metal-on-Polyethylene Bearing"],
    compatibleSurgeries: ["hip-replacement-total", "hip-replacement-partial", "hip-revision"],
    features: ["Good wear characteristics", "Well-established design", "Suitable for most patients", "Cost-effective"]
  },
  {
    id: "hip-economy",
    name: "Economy Hip Implant",
    manufacturer: "Yogeshwar Implants",
    origin: "Indian",
    tier: "Economy",
    description: "Cost-effective hip implant for budget-conscious patients with moderate activity levels",
    price: 60000,
    warranty: 5,
    longevity: 10,
    materials: ["Stainless Steel", "Polyethylene"],
    compatibleSurgeries: ["hip-replacement-total"],
    features: ["Affordable option", "Suitable for less active, elderly patients", "Made in India"]
  },
  {
    id: "shoulder-premium",
    name: "Premium Shoulder Implant",
    manufacturer: "Zimmer Biomet",
    origin: "Imported",
    tier: "Premium",
    description: "Advanced imported shoulder implant with reverse design for complex cases",
    price: 160000,
    warranty: 15,
    longevity: 20,
    materials: ["Titanium Alloy", "Highly Cross-linked Polyethylene"],
    compatibleSurgeries: ["shoulder-replacement-total", "shoulder-replacement-reverse"],
    features: ["Reverse design for rotator cuff deficiency", "Excellent range of motion", "Highly customizable", "Advanced bearing technology"]
  },
  {
    id: "shoulder-standard",
    name: "Standard Shoulder Implant",
    manufacturer: "Auxein Medical",
    origin: "Indian",
    tier: "Standard",
    description: "Reliable anatomic shoulder implant for primary osteoarthritis cases",
    price: 85000,
    warranty: 10,
    longevity: 15,
    materials: ["Cobalt-Chromium Alloy", "Polyethylene"],
    compatibleSurgeries: ["shoulder-replacement-total", "shoulder-replacement-partial"],
    features: ["Anatomic design", "Good stability", "Reliable performance", "Cost-effective"]
  },
  {
    id: "elbow-premium",
    name: "Premium Elbow Implant",
    manufacturer: "Wright Medical",
    origin: "Imported",
    tier: "Premium",
    description: "High-performance elbow replacement system with semi-constrained design",
    price: 140000,
    warranty: 12,
    longevity: 18,
    materials: ["Cobalt-Chromium Alloy", "Ultra-High Molecular Weight Polyethylene"],
    compatibleSurgeries: ["elbow-replacement-total"],
    features: ["Semi-constrained design", "Excellent stability", "Preserves bone stock", "Anatomic articulation"]
  },
  {
    id: "ankle-premium",
    name: "Premium Ankle Implant",
    manufacturer: "Stryker",
    origin: "Imported",
    tier: "Premium",
    description: "Mobile-bearing total ankle replacement system for maximum function",
    price: 170000,
    warranty: 12,
    longevity: 15,
    materials: ["Titanium Alloy", "Cobalt-Chromium", "Mobile Polyethylene Bearing"],
    compatibleSurgeries: ["ankle-replacement-total"],
    features: ["Mobile bearing design", "Anatomic articulation", "Bone-conserving", "Excellent range of motion"]
  },
  {
    id: "spine-premium",
    name: "Premium Spinal Disc Implant",
    manufacturer: "Medtronic",
    origin: "Imported",
    tier: "Premium",
    description: "Advanced artificial disc replacement for maintaining motion in the spine",
    price: 200000,
    warranty: 10,
    longevity: 15,
    materials: ["Titanium Endplates", "Polyethylene Core"],
    compatibleSurgeries: ["spine-disc-replacement"],
    features: ["Preserves motion", "Reduces adjacent segment degeneration", "Anatomic design", "Minimizes bone removal"]
  },
  {
    id: "spine-standard",
    name: "Standard Spinal Fusion Implant",
    manufacturer: "Jayon Implants",
    origin: "Indian",
    tier: "Standard",
    description: "Reliable spinal fusion cage system for degenerative disc disease",
    price: 100000,
    warranty: 10,
    longevity: 20,
    materials: ["PEEK (Polyetheretherketone)", "Titanium Coating"],
    compatibleSurgeries: ["spine-fusion"],
    features: ["Promotes bone ingrowth", "Radiolucent material", "Anatomic fit", "Stable fixation"]
  }
];
